use serde::{Deserialize, Serialize};

use crate::error::{AppError, Result};

// 🦀 `const` declares a compile-time constant.  `&str` is a *string slice* —
//    an immutable reference to UTF-8 text stored in the binary.  Unlike `String`
//    (which is heap-allocated and owned), `&str` is just a pointer + length with
//    no ownership.  The `'static` lifetime is implied here: the data lives for the
//    entire program.
const KEYCHAIN_SERVICE: &str = "dev.ember.oauth";

// 🦀 `#[derive(...)]` auto-generates trait implementations via macros:
//    - `Debug`     → lets you print with `{:?}`, useful in tests and logs.
//    - `Clone`     → enables `.clone()` to create an independent copy of the value.
//    - `PartialEq` → enables `==` and `!=` comparisons between two `StoredToken`s;
//                    used by the `assert_eq!` in `serde_round_trips` below.
//    - `Serialize` / `Deserialize` (from serde) → convert to/from JSON automatically.
//      The field names in the struct become the JSON keys.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StoredToken {
    pub email: String,
    pub access_token: String,
    pub refresh_token: String,
    /// Unix epoch seconds when the access token expires.
    pub expires_at: u64,
}

// 🦀 An `impl` block attaches *methods* to a type.  Methods that take `&self`
//    receive an *immutable borrow* of the value — they can read fields but cannot
//    mutate them, and they do not take ownership (the caller still owns the struct
//    after the call returns).
impl StoredToken {
    /// True if the access token is expired or within `skew_secs` of expiring.
    // 🦀 `&self` is syntactic sugar for `self: &StoredToken`.  The `&` means this
    //    is a borrow — the method reads the struct without consuming it.
    //    `now_secs` and `skew_secs` are plain `u64` values (Copy types), so they
    //    are passed by value with no borrowing needed.
    pub fn is_expired(&self, now_secs: u64, skew_secs: u64) -> bool {
        now_secs + skew_secs >= self.expires_at
    }
}

// 🦀 `account: &str` accepts a *borrowed string slice*.  The caller passes either
//    a `&str` literal or a `&String` (Rust auto-derefs `&String` → `&str`).
//    Using `&str` instead of `String` avoids an unnecessary allocation — we only
//    need to read the value, not own it.
//
// 🦀 `-> Result<()>` is our crate's type alias for `std::result::Result<(), AppError>`.
//    `()` is the *unit type* — like `void` in other languages.  Returning `Ok(())`
//    signals success with no meaningful value.
pub fn save_token(account: &str, token: &StoredToken) -> Result<()> {
    // 🦀 `keyring::Entry::new(...)` returns a `keyring::Result<Entry>`.
    //    The `?` operator is shorthand for: if `Err(e)`, return `Err(e.into())`
    //    from the current function (converting `keyring::Error` → `AppError` via
    //    the `#[from]` impl in error.rs); otherwise unwrap the `Ok` value.
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, account)?;
    // 🦀 `serde_json::to_string` returns `serde_json::Result<String>`, whose error
    //    type is `serde_json::Error` — not `AppError`.  We use `.map_err(...)` to
    //    convert it: the closure receives the error `e` and wraps it in
    //    `AppError::Other(e.to_string())`.  Then `?` propagates if it's still `Err`.
    let json = serde_json::to_string(token).map_err(|e| AppError::Other(e.to_string()))?;
    entry.set_password(&json)?;
    Ok(())
}

// 🦀 `-> Result<Option<StoredToken>>` combines two layers of "might be absent":
//    - The outer `Result<_, AppError>` signals *errors* (Keychain I/O failure, etc.).
//    - The inner `Option<StoredToken>` signals *absence without error* — no entry
//      stored yet.  This is the idiomatic way to distinguish "not found" from "failed".
pub fn load_token(account: &str) -> Result<Option<StoredToken>> {
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, account)?;
    // 🦀 `match` exhaustively handles every variant of the `Result` returned by
    //    `get_password()`.  Rust requires all variants to be covered — the compiler
    //    will error if any arm is missing.
    match entry.get_password() {
        // 🦀 `Ok(json)` *destructures* the Ok variant, binding the inner String to `json`.
        Ok(json) => Ok(Some(
            serde_json::from_str(&json).map_err(|e| AppError::Other(e.to_string()))?,
        )),
        // 🦀 `Err(keyring::Error::NoEntry)` matches *specifically* the NoEntry variant.
        //    This is pattern matching on an enum variant with no payload.  We return
        //    `Ok(None)` — "no token stored" is not an error, just absence.
        Err(keyring::Error::NoEntry) => Ok(None),
        // 🦀 The wildcard arm `Err(e)` catches any other keyring error.
        //    `e.into()` converts `keyring::Error` → `AppError` via the `From` impl
        //    generated by `#[from]` in error.rs.  Then `Err(...)` wraps it.
        Err(e) => Err(e.into()),
    }
}

/// Remove the stored token for `account` from the Keychain. A missing entry is treated
/// as success (idempotent), mirroring `load_token`'s NoEntry handling.
pub fn delete_token(account: &str) -> Result<()> {
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, account)?;
    // 🦀 `delete_credential()` (keyring 3) removes the secret. We `match` so a NoEntry
    //    (nothing stored) is `Ok(())` — disconnect should be idempotent. Any other error
    //    converts to AppError via `e.into()`.
    match entry.delete_credential() {
        Ok(()) => Ok(()),
        Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(e.into()),
    }
}

// 🦀 The credentials are stored in the SAME Keychain service as the OAuth tokens, but
//    under a RESERVED account key that can't collide with a real account email (emails
//    contain '@'; this key does not).
const CLIENT_CREDS_KEY: &str = "__google_client__";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct StoredCredentials {
    client_id: String,
    client_secret: String,
}

/// Save the user-supplied Google OAuth client id + secret to the Keychain.
pub fn save_credentials(client_id: &str, client_secret: &str) -> Result<()> {
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, CLIENT_CREDS_KEY)?;
    let creds = StoredCredentials {
        client_id: client_id.to_string(),
        client_secret: client_secret.to_string(),
    };
    let json = serde_json::to_string(&creds).map_err(|e| AppError::Other(e.to_string()))?;
    entry.set_password(&json)?;
    Ok(())
}

/// Load the stored client id + secret, if any. Missing entry → `Ok(None)`.
pub fn load_credentials() -> Result<Option<(String, String)>> {
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, CLIENT_CREDS_KEY)?;
    match entry.get_password() {
        Ok(json) => {
            let c: StoredCredentials =
                serde_json::from_str(&json).map_err(|e| AppError::Other(e.to_string()))?;
            Ok(Some((c.client_id, c.client_secret)))
        }
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e.into()),
    }
}

/// Remove the stored client credentials. Missing entry is success (idempotent).
pub fn delete_credentials() -> Result<()> {
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, CLIENT_CREDS_KEY)?;
    match entry.delete_credential() {
        Ok(()) => Ok(()),
        Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(e.into()),
    }
}

// 🦀 `#[cfg(test)]` is a *conditional compilation* attribute.  The `mod tests`
//    block and everything inside it is compiled ONLY when running `cargo test`.
//    In a normal `cargo build`, this entire block is stripped out, so test helpers
//    and `#[test]` functions never appear in the production binary.
#[cfg(test)]
mod tests {
    // 🦀 `use super::StoredToken;` imports `StoredToken` from the parent module
    //    (`tokens`).  Inside a nested `mod tests`, `super` refers to the enclosing
    //    module, so `super::StoredToken` is `crate::auth::tokens::StoredToken`.
    use super::StoredToken;

    fn tok(expires_at: u64) -> StoredToken {
        StoredToken {
            email: "a@b.com".into(),
            access_token: "x".into(),
            refresh_token: "r".into(),
            expires_at,
        }
    }

    #[test]
    fn expired_when_within_skew() {
        let t = tok(1000);
        assert!(t.is_expired(950, 60)); // 950 + 60 >= 1000
        assert!(!t.is_expired(900, 60)); // 900 + 60 < 1000
    }

    #[test]
    fn serde_round_trips() {
        let t = tok(1234);
        let json = serde_json::to_string(&t).unwrap();
        let back: StoredToken = serde_json::from_str(&json).unwrap();
        assert_eq!(t, back);
    }
}
